#%RAML 1.0 NamedExample
value:
  -
    airline: Indigo
    flightCode: IND101
    fromAirportCode: HYD
    toAirportCode: BLR
    departureDate: 27/12/2019
    emptySeats: 0
    totalSeats: 200
    price: 199
    planeType: Indigo 737
  -
    airline: Indigo
    flightCode: IND102
    fromAirportCode: HYD
    toAirportCode: BLR
    departureDate: 27/12/2019
    emptySeats: 24
    totalSeats: 350
    price: 450
    planeType: Indigo 747
